export const protocolAdminAbi = [
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function MAX_FEE_BPS() view returns (uint256)",
  "function SETTLEMENT_ROLE() view returns (bytes32)",
  "function acceptOffer(uint256 advanceId)",
  "function advanceCount() view returns (uint256)",
  "function advances(uint256 tokenId) view returns (uint256 requestTokenId,uint256 offerTokenId,address sponsor,address beneficiary,address settlementRecipient,uint64 fundedAt,uint64 acceptedAt,uint64 closedAt,uint256 recoveredAmount,uint256 creatorPayout,uint8 status,string metadataUri)",
  "function approve(address to,uint256 tokenId)",
  "function balanceOf(address owner) view returns (uint256)",
  "function cancelOffer(uint256 advanceId)",
  "function createRequest((address asset,uint256 principal,uint256 repaymentAmount,uint64 fundingDeadline,uint64 repaymentDueAt,bytes32 termsHash,string metadataUri,string artizenProjectUrl,string artizenFundUrl) terms) returns (uint256 requestTokenId)",
  "function creatorRequestTokenIds(address creator) view returns (uint256[])",
  "function emailAssetStats(bytes32 emailHash,address asset) view returns (uint256 principalFunded,uint256 principalBorrowed,uint256 amountRepaid,uint256 amountRecovered,uint256 creatorPayouts)",
  "function emailLenderAdvanceIds(bytes32 emailHash) view returns (uint256[])",
  "function emailRequestTokenIds(bytes32 emailHash) view returns (uint256[])",
  "function emailStats(bytes32 emailHash) view returns (uint256 requestsCreated,uint256 offersFunded,uint256 advancesAccepted,uint256 advancesCompleted,uint256 defaults,uint256 outcomesSubmitted)",
  "function expireOffer(uint256 advanceId)",
  "function fundRequest(uint256 requestTokenId,string metadataUri) payable returns (uint256 advanceId)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role,address account)",
  "function hasRole(bytes32 role,address account) view returns (bool)",
  "function isApprovedForAll(address owner,address operator) view returns (bool)",
  "function lenderAdvanceIds(address lender) view returns (uint256[])",
  "function name() view returns (string)",
  "function outcome(uint256 advanceId,address participant) view returns ((uint8 rating,bytes32 outcomeHash,string metadataUri,uint64 submittedAt))",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function profiles(address account) view returns (bytes32 emailHash,bytes32 agentDidHash,string profileUri)",
  "function recoverUnencumberedFunds(address asset,address recipient,uint256 amount)",
  "function registerProfile(bytes32 emailHash,bytes32 agentDidHash,string profileUri)",
  "function renounceRole(bytes32 role,address callerConfirmation)",
  "function repay(uint256 advanceId) payable",
  "function requests(uint256 requestTokenId) view returns (address creator,bytes32 creatorEmailHash,address asset,uint256 principal,uint256 repaymentAmount,uint64 createdAt,uint64 fundingDeadline,uint64 repaymentDueAt,bytes32 termsHash,string metadataUri,string artizenProjectUrl,string artizenFundUrl,uint256 advanceId)",
  "function revokeRole(bytes32 role,address account)",
  "function safeTransferFrom(address from,address to,uint256 tokenId)",
  "function safeTransferFrom(address from,address to,uint256 tokenId,bytes data)",
  "function setApprovalForAll(address operator,bool approved)",
  "function setAssetSupported(address asset,bool supported)",
  "function setSettlementRecipient(uint256 advanceId,address destination)",
  "function settleFromPayout(uint256 advanceId,uint256 grossPayout) payable",
  "function submitOutcome(uint256 advanceId,uint8 rating,bytes32 outcomeHash,string metadataUri)",
  "function supportedAssets(address asset) view returns (bool)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenCount() view returns (uint256)",
  "function tokenRecords(uint256 tokenId) view returns (uint8 kind,uint256 requestTokenId,uint256 advanceId)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function totalLiabilities(address asset) view returns (uint256)",
  "function transferFrom(address from,address to,uint256 tokenId)",
  "function walletAssetStats(address wallet,address asset) view returns (uint256 principalFunded,uint256 principalBorrowed,uint256 amountRepaid,uint256 amountRecovered,uint256 creatorPayouts)",
  "function walletForEmailHash(bytes32 emailHash) view returns (address)",
  "function walletStats(address wallet) view returns (uint256 requestsCreated,uint256 offersFunded,uint256 advancesAccepted,uint256 advancesCompleted,uint256 defaults,uint256 outcomesSubmitted)"
];

export const networkRegistryAdminAbi = [
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function HEARTBEAT_INTERVAL() view returns (uint256)",
  "function MIN_MONTHLY_CHECKS() view returns (uint256)",
  "function MONTHLY_NODE_REWARD() view returns (uint256)",
  "function NETWORK_ADMIN_ROLE() view returns (bytes32)",
  "function NODE_CHECKER_ROLE() view returns (bytes32)",
  "function deactivateContent(uint256 publicationId)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role,address account)",
  "function hasRole(bytes32 role,address account) view returns (bool)",
  "function heartbeat(uint256 nodeId,uint256 month,bytes32 challengeHash,bytes32 sampleProofHash,uint256 sampleCount,string softwareVersion)",
  "function markMonthlyRewardPaid(uint256 nodeId,uint256 month)",
  "function nodeRewardAmount() view returns (uint256)",
  "function nodeRewardAsset() view returns (address)",
  "function nodeRewardFundId() view returns (bytes32)",
  "function nodeRewardRouter() view returns (address)",
  "function monthChallenges(uint256 month) view returns (bytes32)",
  "function monthStats(uint256 nodeId,uint256 month) view returns (uint32 checks,uint64 firstHeartbeat,uint64 lastHeartbeat,bytes32 lastSampleProofHash,bool rewardPaid)",
  "function nodeCount() view returns (uint256)",
  "function nodes(uint256 nodeId) view returns (address operator,bytes32 nodeDidHash,bytes32 peerIdHash,string softwareVersion,bool approved,bool active)",
  "function operatorNodeIds(address operator) view returns (uint256[])",
  "function profileReader() view returns (address)",
  "function publicationCount() view returns (uint256)",
  "function publications(uint256 publicationId) view returns (address publisher,uint8 kind,string cid,bytes32 contentHash,bytes32 agentDidHash,bytes32 statusHash,uint64 publishedAt,bool active)",
  "function publishContent(uint8 kind,string cid,bytes32 contentHash,bytes32 agentDidHash,string artizenProjectUrl,string artizenFundUrl) returns (uint256 publicationId)",
  "function publisherPublicationIds(address publisher) view returns (uint256[])",
  "function recordNodeCheck(uint256 nodeId,uint256 month,bytes32 challengeHash,bytes32 sampleProofHash,uint256 sampleCount)",
  "function registerNode(bytes32 nodeDidHash,bytes32 peerIdHash,string softwareVersion) returns (uint256 nodeId)",
  "function renounceRole(bytes32 role,address callerConfirmation)",
  "function revokeRole(bytes32 role,address account)",
  "function rewardEligible(uint256 nodeId,uint256 month) view returns (bool)",
  "function setMonthChallenge(uint256 month,bytes32 challengeHash)",
  "function setNodeRewardPayout(address routerAddress,bytes32 fundId,address asset,uint256 amount)",
  "function setNodeActive(uint256 nodeId,bool active)",
  "function setNodeApproval(uint256 nodeId,bool approved)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function updateContentStatus(uint256 publicationId,bytes32 statusHash)",
  "function recoverUnencumberedFunds(address asset,address payable recipient,uint256 amount)"
];
